// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositorio.Contexto;

namespace Repositorio.Migrations
{
    [DbContext(typeof(ContextoEntity))]
    partial class ContextoEntityModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Entidades.Agendamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime")
                        .HasColumnName("DATACRIACAO");

                    b.Property<string>("DiaDaSemanaColeta")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("DIADASEMANACOLETA");

                    b.Property<int>("HoraColeta")
                        .HasColumnType("integer")
                        .HasColumnName("HORACOLETA");

                    b.Property<Guid>("IdColetor")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDCOLETOR");

                    b.Property<Guid>("IdItem")
                        .HasMaxLength(100)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IDITEM");

                    b.Property<int>("MinutoColeta")
                        .HasColumnType("integer")
                        .HasColumnName("MINUTOCOLETA");

                    b.HasKey("Id");

                    b.ToTable("AGENDAMENTO");
                });
#pragma warning restore 612, 618
        }
    }
}
